FROM opendatacube/datacube-core

RUN pip3 install fiona shapely

RUN apt-get update && apt-get install -y wget unzip

WORKDIR /tmp/code
RUN wget https://github.com/data-cube/dea-dashboard/archive/develop.zip -O /tmp/dashboard.zip \
    && unzip /tmp/dashboard.zip \
    && mv /tmp/code/dea-dashboard-develop /code

WORKDIR /code

RUN pip3 install flask gunicorn
RUN python3 setup.py install

CMD gunicorn -b '0.0.0.0:80' -w 5 --timeout 300 cubedash:app
