name: landsat_8_USARD
description: Landsat 8 US/ARD Product Definition
metadata_type: eo

metadata:
    platform:
        code: LANDSAT_8
    instrument:
        name: OLI_TIRS
    product_type: USARD
    format:
        name: GeoTiff
measurements:
    - name: 'coastal_aerosol'
      aliases: [band_1, coastal_aerosol]
      dtype: int16
      nodata: -9999
      units: '1'

    - name: 'blue'
      aliases: [band_2, blue]
      dtype: int16
      nodata: -9999
      units: '1'

    - name: 'green'
      aliases: [band_3, green]
      dtype: int16
      nodata: -9999
      units: '1'

    - name: 'red'
      aliases: [band_4, red]
      dtype: int16
      nodata: -9999
      units: '1'

    - name: 'nir'
      aliases: [band_5, nir]
      dtype: int16
      nodata: -9999
      units: '1'

    - name: 'swir1'
      aliases: [band_6, swir1]
      dtype: int16
      nodata: -9999
      units: '1'

    - name: 'swir2'
      aliases: [band_7, swir2]
      dtype: int16
      nodata: -9999
      units: '1'

    - name: 'pixel_qa'
      aliases: [PIXELQA, pixel_qa]
      dtype: int16
      nodata: 0
      units: '1'
      flags_definition:
        fill:
          bits: [0]
          description: Fill
          values: {0: false, 1: true}
        clear:
          bits: [1]
          description: Clear
          values: {0: false, 1: true}
        water:
          bits: [2]
          description: Water
          values: {0: false, 1: true}
        cloud:
          bits: [5]
          description: Cloud
          values: {0: false, 1: true}
